title: Artez Chapman's Blog
description: Cloud, DevOps, and Infrastructure Learning
url: "https://blog.artezchapman.com"
author: Artez Chapman
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalink structure
permalink: /:categories/:year/:month/:day/:title/

# Build settings
markdown: kramdown

# Social links
github_username: artezchapman
linkedin_username: artezchapman

# Show excerpts on home page
show_excerpts: true
